;this file for FamiTone2 library generated by text2data tool

p_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,253,211

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env2,@env0,@env0
	.byte $00
	.byte $70 ;instrument $03
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $05
	.word @env4,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $06
	.word @env5,@env0,@env0
	.byte $00
	.byte $b0 ;instrument $07
	.word @env6,@env0,@env0
	.byte $00
	.byte $70 ;instrument $08
	.word @env6,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $ce,$c6,$c4,$c3,$c2,$c0,$00,$05
@env2:
	.byte $ca,$c9,$c8,$c7,$c6,$c5,$02,$c4,$c4,$c3,$c2,$c2,$c1,$02,$c0,$00
	.byte $0e
@env3:
	.byte $c4,$0b,$c3,$12,$c2,$1b,$c1,$1a,$c1,$00,$08
@env4:
	.byte $c4,$c4,$c0,$00,$02
@env5:
	.byte $c5,$0d,$c4,$16,$c3,$15,$c2,$0e,$c1,$0b,$c1,$00,$0a
@env6:
	.byte $c8,$c8,$c0,$00,$02


@song0ch0:
	.byte $fb,$02
@song0ch0loop:
@ref0:
	.byte $88,$24,$85,$84,$2c,$85,$32,$85,$88,$24,$85,$84,$2c,$85,$32,$85
	.byte $88,$24,$85,$84,$2c,$85,$88,$28,$85,$84,$30,$85,$36,$85,$88,$28
	.byte $85,$84,$30,$85,$36,$85,$88,$28,$85,$84,$30,$85,$88,$2c,$85,$84
	.byte $32,$85,$3a,$85,$88,$2c,$85,$84,$32,$85,$3a,$85,$88,$2c,$85,$84
	.byte $32,$85,$88,$2c,$85,$84,$32,$85,$3a,$85,$88,$2c,$85,$84,$32,$85
	.byte $3a,$85,$88,$2c,$85,$84,$32,$85
@ref1:
	.byte $88,$24,$85,$84,$2c,$85,$32,$85,$88,$24,$85,$84,$2c,$85,$32,$85
	.byte $88,$24,$85,$84,$2c,$85,$88,$28,$85,$84,$30,$85,$36,$85,$88,$28
	.byte $85,$84,$30,$85,$36,$85,$88,$28,$85,$84,$30,$85,$88,$2c,$85,$84
	.byte $32,$85,$3a,$85,$88,$2c,$85,$84,$32,$85,$3a,$85,$88,$2c,$85,$84
	.byte $32,$85,$88,$2c,$85,$84,$32,$85,$3a,$85,$88,$2c,$85,$8a,$32,$00
	.byte $83,$32,$00,$83,$8c,$32,$00,$83,$32,$00,$83
	.byte $ff,$40
	.word @ref0
	.byte $ff,$40
	.word @ref0
	.byte $ff,$40
	.word @ref0
	.byte $ff,$44
	.word @ref1
	.byte $ff,$40
	.word @ref0
	.byte $ff,$40
	.word @ref0
	.byte $fd
	.word @song0ch0loop

@song0ch1:
@song0ch1loop:
@ref8:
	.byte $88,$28,$bd,$24,$bd,$22,$bd,$14,$8d,$18,$8d,$1a,$8d,$10,$8d
@ref9:
	.byte $28,$bd,$24,$bd,$22,$bd,$14,$8d,$18,$8d,$1a,$8d,$10,$8d
	.byte $ff,$0e
	.word @ref9
	.byte $ff,$0e
	.word @ref9
	.byte $ff,$0e
	.word @ref9
	.byte $ff,$0e
	.word @ref9
	.byte $ff,$0e
	.word @ref9
	.byte $ff,$0e
	.word @ref9
	.byte $fd
	.word @song0ch1loop

@song0ch2:
@song0ch2loop:
@ref16:
	.byte $00,$f9,$f9,$89
@ref17:
	.byte $00,$f9,$f9,$89
@ref18:
	.byte $88,$24,$bd,$28,$bd,$2c,$f9,$83
@ref19:
	.byte $24,$bd,$28,$bd,$2c,$f9,$83
	.byte $ff,$07
	.word @ref19
@ref21:
	.byte $24,$bd,$28,$bd,$2c,$bd,$32,$8d,$30,$8d,$2c,$8d,$22,$8d
@ref22:
	.byte $24,$bd,$28,$bd,$2c,$bd,$2c,$8d,$30,$8d,$32,$8d,$28,$8d
	.byte $ff,$07
	.word @ref19
	.byte $fd
	.word @song0ch2loop

@song0ch3:
@song0ch3loop:
@ref24:
	.byte $00,$f9,$f9,$89
@ref25:
	.byte $f9,$d5,$80,$20,$8d,$20,$85,$20,$85,$86,$14,$85,$14,$85
@ref26:
	.byte $80,$20,$95,$20,$85,$82,$10,$8d,$86,$14,$8d,$80,$20,$95,$20,$85
	.byte $82,$10,$8d,$86,$14,$8d,$80,$20,$95,$20,$85,$82,$10,$8d,$86,$14
	.byte $8d,$80,$20,$95,$20,$85,$82,$10,$8d,$86,$14,$8d
	.byte $ff,$20
	.word @ref26
	.byte $ff,$20
	.word @ref26
@ref29:
	.byte $80,$20,$95,$20,$a5,$20,$95,$20,$a5,$20,$95,$20,$b5,$20,$8d,$20
	.byte $85,$20,$85,$86,$14,$85,$14,$85
	.byte $ff,$20
	.word @ref26
	.byte $ff,$20
	.word @ref26
	.byte $fd
	.word @song0ch3loop

@song0ch4:
@song0ch4loop:
@ref32:
	.byte $f9,$f9,$8b
@ref33:
	.byte $f9,$f9,$8b
@ref34:
	.byte $f9,$f9,$8b
@ref35:
	.byte $f9,$f9,$8b
@ref36:
	.byte $f9,$f9,$8b
@ref37:
	.byte $f9,$f9,$8b
@ref38:
	.byte $f9,$f9,$8b
@ref39:
	.byte $f9,$f9,$8b
	.byte $fd
	.word @song0ch4loop
